[package]
name = "blithaven"
version = "0.1.0"
edition = "2021"
description = "Complex and insanely fast 2D rendering library"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
earcutr = "*"