[package]
name = "blithaven"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "2d render"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
earcutr = "*"
rand = "0.8.5"
image = "0.24.7"
