[package]
name = "blithaven_rewrite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
earcutr = "*"
rand = "0.8.5"
image = "0.24.7"
