[package]
name = "blithaven"
version = "0.2.1"
edition = "2021"
description = "Complex and insanely fast 2D rendering library"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.32.1"
earcutr = "0.4.2"